package lab9.task2;

import javax.swing.*;

public class Main {
    public static void main(String[] args) {
      Counter counter = new Counter();
        counter.parse("Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Tortor condimentum lacinia quis vel eros donec ac odio. Metus vulputate eu scelerisque felis imperdiet proin fermentum leo. Et egestas quis ipsum suspendisse ultrices. Accumsan lacus vel facilisis volutpat est velit. Vestibulum morbi blandit cursus risus at ultrices mi tempus. Risus nec feugiat in fermentum posuere urna nec tincidunt praesent. Pretium nibh ipsum consequat nisl. Dui sapien eget mi proin sed libero enim. Quis blandit turpis cursus in hac habitasse platea dictumst.\n" +
                "\n" +
                "Potenti nullam ac tortor vitae purus faucibus ornare. In arcu cursus euismod quis viverra nibh. Gravida quis blandit turpis cursus in hac. Nunc id cursus metus aliquam eleifend mi in nulla posuere. Aliquet bibendum enim facilisis gravida. Lacus vestibulum sed arcu non odio euismod. Fermentum et sollicitudin ac orci phasellus egestas tellus rutrum. Ut tortor pretium viverra suspendisse. Ullamcorper eget nulla facilisi etiam dignissim. Et netus et malesuada fames ac turpis. Ipsum consequat nisl vel pretium lectus quam id leo. Mattis nunc sed blandit libero volutpat sed cras ornare. Fringilla urna porttitor rhoncus dolor purus. Convallis tellus id interdum velit laoreet id donec. Pretium lectus quam id leo in vitae turpis massa. Sem fringilla ut morbi tincidunt augue interdum. Etiam sit amet nisl purus in mollis nunc sed id. Aliquam ut porttitor leo a diam. Mollis nunc sed id semper. Gravida dictum fusce ut placerat orci nulla pellentesque.\n" +
                "\n" +
                "Euismod elementum nisi quis eleifend. Mattis aliquam faucibus purus in massa tempor nec feugiat nisl. Nec feugiat nisl pretium fusce id. Dignissim suspendisse in est ante in nibh mauris cursus mattis. Purus semper eget duis at tellus at urna. Nunc sed blandit libero volutpat sed cras. Tincidunt arcu non sodales neque sodales ut etiam sit amet. Mattis aliquam faucibus purus in massa tempor nec feugiat. Orci phasellus egestas tellus rutrum tellus pellentesque eu. Tellus molestie nunc non blandit massa enim nec. Donec et odio pellentesque diam volutpat commodo. Cursus in hac habitasse platea dictumst. Gravida arcu ac tortor dignissim convallis aenean.\n" +
                "\n" +
                "Ullamcorper a lacus vestibulum sed. In metus vulputate eu scelerisque felis imperdiet proin. Ornare quam viverra orci sagittis eu volutpat odio facilisis. Eu scelerisque felis imperdiet proin fermentum leo vel orci porta. Placerat in egestas erat imperdiet. Tempus iaculis urna id volutpat lacus laoreet non. Neque vitae tempus quam pellentesque. Arcu vitae elementum curabitur vitae nunc. Tristique senectus et netus et malesuada fames ac turpis egestas. Potenti nullam ac tortor vitae purus. Mattis vulputate enim nulla aliquet porttitor lacus luctus.\n" +
                "\n" +
                "Blandit volutpat maecenas volutpat blandit aliquam. Est velit egestas dui id ornare arcu odio ut sem. Convallis tellus id interdum velit laoreet id donec ultrices. Tristique senectus et netus et malesuada fames ac turpis egestas. Mattis enim ut tellus elementum. In mollis nunc sed id semper risus in. Vitae nunc sed velit dignissim sodales ut eu. Volutpat lacus laoreet non curabitur gravida arcu ac tortor dignissim. Posuere urna nec tincidunt praesent semper feugiat nibh sed pulvinar. Mattis vulputate enim nulla aliquet. Arcu cursus vitae congue mauris rhoncus aenean vel elit scelerisque. Duis tristique sollicitudin nibh sit amet commodo nulla facilisi nullam. Amet est placerat in egestas erat imperdiet sed euismod. Mattis aliquam faucibus purus in massa tempor. Praesent elementum facilisis leo vel fringilla est. Lobortis mattis aliquam faucibus purus in massa tempor. Enim blandit volutpat maecenas volutpat blandit aliquam etiam.\n" +
                "\n" +
                "Tincidunt augue interdum velit euismod in. Libero nunc consequat interdum varius sit amet mattis vulputate enim. Quis auctor elit sed vulputate. Purus ut faucibus pulvinar elementum integer enim neque volutpat ac. Pellentesque elit eget gravida cum sociis natoque penatibus et magnis. Eu ultrices vitae auctor eu augue ut lectus. Dui sapien eget mi proin sed libero enim. Fames ac turpis egestas sed tempus. Sed blandit libero volutpat sed cras ornare arcu dui vivamus. Ipsum dolor sit amet consectetur adipiscing. Nulla facilisi etiam dignissim diam quis enim lobortis scelerisque. Ultrices vitae auctor eu augue ut lectus.\n" +
                "\n" +
                "Dis parturient montes nascetur ridiculus mus mauris vitae. Tincidunt nunc pulvinar sapien et ligula ullamcorper malesuada. Cursus in hac habitasse platea dictumst. Sit amet consectetur adipiscing elit ut aliquam. Donec ac odio tempor orci dapibus ultrices. Ut ornare lectus sit amet est placerat in egestas. Gravida dictum fusce ut placerat orci nulla pellentesque dignissim enim. Vitae justo eget magna fermentum iaculis eu non diam. Vestibulum morbi blandit cursus risus at ultrices. Faucibus et molestie ac feugiat sed lectus vestibulum mattis ullamcorper. Amet purus gravida quis blandit turpis cursus. Gravida arcu ac tortor dignissim convallis aenean et. Id semper risus in hendrerit. Pretium viverra suspendisse potenti nullam ac. Volutpat consequat mauris nunc congue nisi vitae suscipit tellus mauris.\n" +
                "\n" +
                "Turpis nunc eget lorem dolor sed viverra ipsum. Pretium fusce id velit ut tortor pretium viverra. Ultrices mi tempus imperdiet nulla. Augue mauris augue neque gravida in fermentum et sollicitudin. Consectetur lorem donec massa sapien faucibus. Eget nunc scelerisque viverra mauris in aliquam sem. Sollicitudin nibh sit amet commodo nulla facilisi nullam vehicula ipsum. Dui id ornare arcu odio ut sem. Orci nulla pellentesque dignissim enim sit amet venenatis urna. Eros donec ac odio tempor orci dapibus. Feugiat sed lectus vestibulum mattis ullamcorper. Dui sapien eget mi proin sed. Turpis egestas pretium aenean pharetra magna ac placerat. Penatibus et magnis dis parturient montes nascetur ridiculus mus mauris. Egestas egestas fringilla phasellus faucibus scelerisque eleifend. Porta non pulvinar neque laoreet suspendisse interdum consectetur. Aliquet nibh praesent tristique magna sit amet purus. Dolor magna eget est lorem ipsum dolor sit amet consectetur.\n" +
                "\n" +
                "Pretium nibh ipsum consequat nisl vel. Pellentesque diam volutpat commodo sed egestas. Faucibus in ornare quam viverra. Integer enim neque volutpat ac tincidunt vitae semper quis. Eu lobortis elementum nibh tellus molestie nunc non blandit massa. Gravida in fermentum et sollicitudin. Cras pulvinar mattis nunc sed blandit libero. Tempus quam pellentesque nec nam aliquam sem et tortor consequat. Et sollicitudin ac orci phasellus egestas tellus rutrum. Mattis aliquam faucibus purus in massa tempor nec. Ultricies lacus sed turpis tincidunt id aliquet. Aliquet nibh praesent tristique magna sit. Diam sit amet nisl suscipit adipiscing bibendum est. Tellus in metus vulputate eu scelerisque.\n" +
                "\n" +
                "Id eu nisl nunc mi ipsum. Tincidunt id aliquet risus feugiat in ante. Elementum sagittis vitae et leo duis ut diam quam. Phasellus faucibus scelerisque eleifend donec pretium vulputate sapien nec. Aliquet enim tortor at auctor urna nunc. Gravida in fermentum et sollicitudin ac orci phasellus. Metus dictum at tempor commodo ullamcorper a lacus vestibulum. In tellus integer feugiat scelerisque varius morbi enim nunc. Maecenas volutpat blandit aliquam etiam erat velit scelerisque in dictum. Enim blandit volutpat maecenas volutpat blandit aliquam. Odio eu feugiat pretium nibh ipsum consequat. Est lorem ipsum dolor sit. Volutpat lacus laoreet non curabitur. At consectetur lorem donec massa sapien faucibus et molestie. Purus non enim praesent elementum facilisis leo vel fringilla est. Sit amet luctus venenatis lectus.");


        counter.printWordCounts();
        System.out.println("Word count of 'Lorem': " + counter.getCount("Lorem"));
        System.out.println("Unique words: " + counter.getUniqueWords());
        counter.reset();
        System.out.println("After reset:");
        counter.printWordCounts();



    }
}
